layout_spectrum: 0.05564924
color:
  saturation: 0.7133221
  brandStrength: 0.360691
  lightness: 0.3726813
  rhythmicContrast: 0.7546374
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
typography_spectrum: 0.4856661
name: Caper Films
