collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.4856661
color:
  saturation: 0.7133221
  brandStrength: 0.360691
  lightness: 0.3726813
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#6A6A6A'
    - '#A7A7A7'
    - '#2F2F2F'
  rhythmicContrast: 0.7546374
layout_spectrum: 0.05564924
name: Caper Films
